### ISSUE TITLE
File open error

### ISSUE THREAD

**Issue by yumianhuli2** [ebadi/OpenScenarioEditor#10]
Hello!
The following error occurs when I select to open an XOSC file:
osc filename:  /XXX/OpenScenarioEditor/pyesmini/resources/xosc/straight_500m.xosc
disable_ctrls = False , use_viewer =  True , threads =  True , recordFile =  
Traceback (most recent call last):
  File "OpenScenarioEditor.py", line 462, in openxml
    self.gui.load_file(self.xmlfn)
  File "/XXX/OpenScenarioEditor/gui_qt.py", line 1122, in load_file
    self.reload()
  File "/XXX/OpenScenarioEditor/gui_qt.py", line 894, in reload
    oscFile=True)
  File "/XXX/OpenScenarioEditor/pyesmini/pyesmini/pyesmini.py", line 103, in __init__
    self.se = CDLL(dir_path + "/libesminiLib.so")
  File "/XXX/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /XXX/OpenScenarioEditor/pyesmini/pyesmini/libesminiLib.so: cannot open shared object file: No such file or directory

**Comment by ebadi** [comment]
@yumianhuli2 Can you provide more information on how you run the program and more about the environment?

**Comment by yumianhuli2** [comment]
Hi！
I followed the instructions below:
Building and running on Linux
First clone the repository:

git clone https://github.com/ebadi/OpenScenarioEditor ~/OpenScenarioEditor
To build and run on Ubuntu (tested on 20.04), simply run the following command that automatically downloads Environment Simulator Minimalistic (esmini) , PyEsmini and required resources/dependencies.

cd ~/OpenScenarioEditor
./run.sh

But
My OS is :Ubuntu18.04

Error message is: OSError: /XXX/OpenScenarioEditor/pyesmini/pyesmini/libesminiLib.so: cannot open shared object file: No such file or directory. Maybe because of the lack of this file？

Thank you!

**Comment by ebadi** [comment]
>> Maybe because of the lack of this file？

Yes, but `run.sh` clone a repository and build that file automatically. Please first **remove** `pyesmini` and report back what is the result of running `run.sh`

**Comment by yumianhuli2** [comment]
Hi!
If first remove pyesmini
A lot of errors like below:
OSError: /XXX/../OpenScenarioEditor/pyesmini/pyesmini/libesminiLib.so: cannot open shared object file: No such file or directory

**Comment by ebadi** [comment]
Please remove the mentioned directory again and run the following
./run.sh &> log.txt

And upload the file here.

**Comment by yumianhuli2** [comment]
Hi!
The file is here
[log.txt](https://github.com/ebadi/OpenScenarioEditor/files/8548930/log.txt)

**Comment by ebadi** [comment]
It seems that the pyesmini directory is not removed since I was expecting [this line](https://github.com/ebadi/OpenScenarioEditor/blob/main/run.sh#L6) to be executed. 
Please run the following and upload the log.txt again: 
```
rm -rf ~/OpenScenarioEditor
git clone https://github.com/ebadi/OpenScenarioEditor ~/OpenScenarioEditor
cd  ~/OpenScenarioEditor
./run.sh &> log.txt
```

**Comment by yumianhuli2** [comment]
> It seems that the pyesmini directory is not removed since I was expecting [this line](https://github.com/ebadi/OpenScenarioEditor/blob/main/run.sh#L6) to be executed. Please run the following and upload the log.txt again:
> 
> ```
> rm -rf ~/OpenScenarioEditor
> git clone https://github.com/ebadi/OpenScenarioEditor ~/OpenScenarioEditor
> cd  ~/OpenScenarioEditor
> ./run.sh &> log.txt
> ```

Hi! 
Now open the xosc file and the program will not crash,But it doesn't seem to be working yet.
log is below:
[log.txt](https://github.com/ebadi/OpenScenarioEditor/files/8551072/log.txt)


And where is the link to the previous C++ repo version?Thank U!

**Comment by ebadi** [comment]
>  the link to the previous C++ repo version?

What do you mean? Which version? 

I inspected the log file but found nothing. Let's try these instead:

```
cd ~
rm -rf ~/OpenScenarioEditor
git clone https://github.com/ebadi/OpenScenarioEditor ~/OpenScenarioEditor  > ~/log0.txt
cd  ~/OpenScenarioEditor
sudo apt install git python3-pip python3-pyqt5  ;     pip3 install PyQt5  > ~/log1.txt
git clone https://github.com/ebadi/pyesmini pyesmini > ~/log2.txt
cd pyesmini ; ./build.sh > ~/log3.txt 
cd ~
python3 OpenScenarioEditor.py > ~/log4.txt 
```

**Comment by yumianhuli2** [comment]
hi!
logs are below:
log0 and log2 are empty
[log1.txt](https://github.com/ebadi/OpenScenarioEditor/files/8564839/log1.txt)
[log3.txt](https://github.com/ebadi/OpenScenarioEditor/files/8564844/log3.txt)
[log4.txt](https://github.com/ebadi/OpenScenarioEditor/files/8564845/log4.txt)

**Comment by ebadi** [comment]
As you see in log3.txt some packages are still not installed. Run these commands to installed all dependence.

```
sudo apt install build-essential git pkg-config libgl1-mesa-dev libpthread-stubs0-dev libjpeg-dev libxml2-dev libpng-dev libtiff5-dev libgdal-dev libpoppler-dev libdcmtk-dev libgstreamer1.0-dev libgtk2.0-dev libcairo2-dev libpoppler-glib-dev libxrandr-dev libxinerama-dev curl cmake
sudo apt install git python3-pip python3-pyqt5 
```
and try again these commands:
https://github.com/ebadi/OpenScenarioEditor/issues/10#issuecomment-1108087320

**Comment by xfqbuaa** [comment]
Please check /pyesmini/build.sh 
1, the tag should be ec2f3e7256c97d32b1a97f0cb8b9bf7f5085bc7e

**Comment by ebadi** [comment]
Hi @xfqbuaa  , @yumianhuli2 , thanks for reporting this issue but I have to inform you that this project is no longer actively maintained. 
I have shifted my focus to a new project. Please check out [OpenScenarioDrive](https://github.com/ebadi/OpenScenarioDrive) for the latest work and updates. Please try this tool and let me know what you think.
